services:
  api:
    image: eclipse-temurin:23-jdk-alpine
    container_name: api
    volumes:
      - ./target/Equoterapia-0.0.1-SNAPSHOT.jar:/app/equoterapiaAPI.jar
    command: [ "java", "-jar", "/app/equoterapiaAPI.jar"]
    ports:
      - "8080:8080"
    expose:
      - '8080'
    environment:
      - DB_URL=jdbc:mysql://db:3306/Equoterapia
    depends_on:
      - db

  db:
    image: mysql
    container_name: database
    environment:
      - MYSQL_DATABASE=Equoterapia
      - MYSQL_USER=equoAdmin
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
    ports:
      - '3306:3306'
    expose:
      - '3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=verysecret
    ports:
      - "8081:80"
    depends_on:
      - db