package com.equoterapia.web.entities.enums;


public enum Roles {
    FONOAUDIOLOGO,
    FISIOTERAPEUTA,
    FISIOTERAPEUTA_COFFITO,
    FONOAUDIOLOGO_CREFONO,
    PSICOLOGO_CRP,
    PSICOPEDAGOGO_CFEP,
    TERAPEUTA_OCUPACIONAL_COFFITO,
    EDUCADOR_FISICO_CREF,
    ASSISTENTE_SOCIAL_CFESS,
    PEDAGOGO,
    PSICOLOGO,
}
